/**
 * Fractional-index string indicator using a fixed large alphabet and midpoint
 * insertion. A single lexicographic string space (no + / - sign seam): the
 * initial indicator sits at the middle of the alphabet, and new indicators are
 * generated by lexicographic midpoint between two existing ones. Unlimited
 * inserts per gap in principle; string length grows ~log_base(gap_insertions)
 * and only at the trailing (fractional) end, so hot-spot inserts stay short.
 *
 * Precision wall: because the alphabet is fixed, a gap can be subdivided at most
 * ~BASE times before no further char fits. At that point `between` / `before` /
 * `after` throw a `PrecisionWallError` and the caller must rebalance (e.g. widen
 * the surrounding gap by reassigning neighbors), exactly as the tuple design
 * splits blocks. This is the known trade-off of pure-string fractional indexing.
 */

const ALPHABET =
	'0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
const BASE = ALPHABET.length;
const FIRST_INDEX = 0;
const MID_INDEX = Math.floor(BASE / 2);
const MID_CHAR = ALPHABET[MID_INDEX];

class PrecisionWallError extends Error {
	constructor(msg: string) {
		super(msg);
		this.name = 'PrecisionWallError';
	}
}

function idx(ch: string | undefined): number {
	// -1 marks the implicit low terminator (a shorter string sorts first)
	if (ch === undefined) return -1;
	return ALPHABET.indexOf(ch);
}

function chr(i: number): string {
	return ALPHABET[i];
}

export type Indicator = string;

export namespace Indicator {
	export const PrecisionWall = PrecisionWallError;

	export const INIT_INDICATOR: Indicator = MID_CHAR;

	/**
	 * Generate an indicator strictly between a and b (a < b). Both must be valid
	 * indicators with a < b. Uses lexicographic midpoint insertion in alphabet-index
	 * space: a shared prefix is descended, a gap > 1 between differing chars yields
	 * an integer midpoint, a prefix relationship yields a char strictly below the
	 * next differing char, and adjacent chars fall back to appending a fractional
	 * mid char. Throws `PrecisionWall` when the gap is exhausted.
	 */
	export function between(a: Indicator, b: Indicator): Indicator {
		if (a === b) {
			throw new Error(
				'Cannot generate an indicator between two equal indicators.',
			);
		}

		let i = 0;
		while (true) {
			const ai = idx(a[i]);
			const bi = idx(b[i]);

			if (ai === bi) {
				// shared prefix: descend into the next position
				i++;
				continue;
			}

			// a < b guarantees ai < bi (terminator -1 is below every alphabet char)
			if (ai === -1) {
				// a is a (possibly empty) prefix of b: place a char strictly below b[i].
				const below = Math.floor(bi / 2);
				if (below <= FIRST_INDEX) {
					// b[i] is the very first alphabet char: no char fits below it.
					throw new PrecisionWall(
						`Gap exhausted inserting below '${b}' after prefix '${a}'.`,
					);
				}
				return a + chr(below);
			}

			if (bi - ai > 1) {
				// integer char strictly between them at this position
				return a.slice(0, i) + chr(Math.floor((ai + bi) / 2));
			}

			// bi === ai + 1 (adjacent): no integer char between them at this position.
			// Append a fractional digit after a[i]; this lands strictly above a and
			// below b only if the digit is < b[i+1] (or b ends here, in which case any
			// digit keeps us below b).
			const nextBi = idx(b[i + 1]);
			if (nextBi === -1 || nextBi > FIRST_INDEX) {
				return a.slice(0, i + 1) + chr(FIRST_INDEX);
			}
			// b[i+1] is also the minimal char: cannot subdivide further here.
			throw new PrecisionWall(
				`Gap exhausted subdividing adjacent chars at position ${i} between '${a}' and '${b}'.`,
			);
		}
	}

	/** Indicator strictly after `ind` (append a mid char at the fractional end). */
	export function after(ind: Indicator): Indicator {
		return ind + MID_CHAR;
	}

	/**
	 * Indicator strictly before `ind`. Decrements the last char by one alphabet
	 * step when possible; if the last char is already minimal, drops it (the
	 * prefix is itself strictly smaller). Throws `PrecisionWall` when `ind` is
	 * already the lowest possible indicator (single minimal char).
	 */
	export function before(ind: Indicator): Indicator {
		if (ind.length === 1) {
			return between('', ind);
		}
		const lastIdx = idx(ind[ind.length - 1]);
		if (lastIdx > FIRST_INDEX) {
			return ind.slice(0, -1) + chr(lastIdx - 1);
		}
		// last char is minimal: the prefix (one char shorter) is strictly smaller
		return ind.slice(0, -1);
	}
}
