// @ts-check
import { defineConfig } from 'astro/config';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import starlight from '@astrojs/starlight';

// The API sidebar is generated by scripts/render.ts into src/generated/sidebar.json
// so the nav always matches the emitted pages. Run `bun run docs:render` (or the
// root `docs:site` script) before building. If it is missing we fall back to an
// empty list so the config still loads.
const sidebarPath = fileURLToPath(new URL('./src/generated/sidebar.json', import.meta.url));
/** @type {any[]} */
const apiSidebar = existsSync(sidebarPath)
  ? JSON.parse(readFileSync(sidebarPath, 'utf8'))
  : [];

// https://astro.build/config
export default defineConfig({
  site: 'https://rimbu.org',
  integrations: [
    starlight({
      title: 'Rimbu',
      description:
        'Immutable, performant, and type-safe collections and tools for TypeScript.',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/rimbu-org/rimbu',
        },
      ],
      customCss: ['./src/styles/api.css'],
      components: {
        Sidebar: './src/components/Sidebar.astro',
      },
      sidebar: [
        {
          label: 'Guides',
          items: [{ label: 'Introduction', slug: 'index' }],
        },
        {
          label: 'API Reference',
          items: apiSidebar,
        },
      ],
    }),
  ],
});
