name: Build all packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - name: Format check
        run: bun format:check

      - name: Lint check
        run: bun lint:check

      - name: Build
        run: bun build

      - name: Test
        run: bun test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
